export const reactPortfolio = [
  {
    id: 1,
    title: "E-commerce",
    img: [
      { path: "images/ecom/1.png" },
      { path: "images/ecom/2.png" },
      { path: "images/ecom/3.png" },
      { path: "images/ecom/4.png" },
      { path: "images/ecom/5.png" },
      { path: "images/ecom/6.png" },
      { path: "images/ecom/7.png" },
    ],
  },
  {
    id: 2,
    title: "Tawsila Platforme",
    img: [
      { path: "images/trajet/1.png" },
      { path: "images/trajet/2.png" },
      { path: "images/trajet/3.png" },
      { path: "images/trajet/4.png" },
      { path: "images/trajet/5.png" },
      { path: "images/trajet/6.png" },
      { path: "images/trajet/7.png" },
      { path: "images/trajet/8.png" },
    ],
  },
  {
    id: 3,
    title: "SanteLib Platforme",
    img: [
      { path: "images/santelib/1.png" },
      { path: "images/santelib/2.png" },
      { path: "images/santelib/3.png" },
      { path: "images/santelib/4.png" },
      { path: "images/santelib/5.png" },
      { path: "images/santelib/6.png" },
      { path: "images/santelib/7.png" },
      { path: "images/santelib/8.png" },
      { path: "images/santelib/9.png" },
      { path: "images/santelib/10.png" },
      { path: "images/santelib/11.png" },
      { path: "images/santelib/12.png" },
      { path: "images/santelib/13.png" },
      { path: "images/santelib/14.png" },
      { path: "images/santelib/15.png" },
      { path: "images/santelib/16.png" },
    ],
  },
  {
    id: 4,
    title: "Forja Platforme",
    img: [
      { path: "images/forja/1.png" },
      { path: "images/forja/2.png" },
      { path: "images/forja/3.png" },
      { path: "images/forja/4.png" },
      { path: "images/forja/5.png" },
      { path: "images/forja/6.png" },
      { path: "images/forja/7.png" },
      { path: "images/forja/8.png" },
      { path: "images/forja/9.png" },
      { path: "images/forja/10.png" },
      { path: "images/forja/11.png" },
      { path: "images/forja/12.png" },
    ],
  },
  {
    id: 5,
    title: "Dentist Platforme",
    img: [
      { path: "images/dentistapp/1.png" },
      { path: "images/dentistapp/2.png" },
      { path: "images/dentistapp/3.png" },
      { path: "images/dentistapp/4.png" },
      { path: "images/dentistapp/5.png" },
      { path: "images/dentistapp/6.png" },
      { path: "images/dentistapp/7.png" },
      { path: "images/dentistapp/8.png" },
      { path: "images/dentistapp/9.png" },
      { path: "images/dentistapp/10.png" },
      { path: "images/dentistapp/11.png" },
    ],
  },
  {
    id: 5,
    title: "Jobify Platforme",
    img: [
      { path: "images/jobify/1.png" },
      { path: "images/jobify/2.png" },
      { path: "images/jobify/3.png" },
      { path: "images/jobify/4.png" },
      { path: "images/jobify/5.png" },
      { path: "images/jobify/6.png" },
      { path: "images/jobify/7.png" },
    ],
  },
];

export const certificats = [
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif2.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif3.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif4.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif5.png",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif7.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif8.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif9.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif10.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif11.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif12.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif13.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif14.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif16.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif17.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif18.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif19.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif20.png",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif21.png",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif22.png",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif23.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif24.jpg",
  },
  {
    id: 1,
    title: "E-commerce",
    path: "images/certif/certif25.png",
  },
];
